export {
  clearAccessToken,
  ensurePassengerAccessToken as ensureAccessToken,
  getAccessToken,
} from '../infrastructure/auth/passengerAuthSession'

export { ApiError, parseApiErrorCode } from '../infrastructure/http/httpClient'

export type {
  AdminKeyInfo,
  AdminPassenger,
  AdminQrSaleAudit,
  AdminSessionUser,
  CurrentUser,
  DriverQrIssueResult,
  DriverQrRedeemResult,
  PassengerQrIssueResult,
  DriverSessionUser,
  PaginatedResult,
  PaginationParams,
  RidePointOverride,
} from '../infrastructure/api/contracts'

export {
  createAdminKey,
  adjustAdminPassengerPoints,
  createDriver,
  createMapMark,
  createServiceZone,
  deleteAdminKey,
  deleteDriver,
  deleteMapMark,
  deleteServiceZone,
  getAdminSession,
  listAdminKeys,
  listAdminPassengers,
  listMapMarks,
  listAdminQrSales,
  listAdminRequests,
  listDrivers,
  loginAdminByKey,
  logoutAdminSession,
  revokeAdminKey,
  rotateAdminKey,
  rotateDriverKey,
  updateAdminKey,
  updateDriver,
  updatePricing,
  updateServiceZone,
  uploadMapMarkPhoto,
  uploadDriverPhoto,
  assignDriverBulk,
  unassignAdminDriver,
  patchAdminRideRoute,
} from '../infrastructure/api/adminApi'

export {
  applyDriverPointAction,
  rateRideAsDriver,
  getDriverCabinet,
  getDriverRideHistory,
  claimDriverRide,
  createDriverOffer,
  cancelDriverOffer,
  listDriverOffers,
  listOfferMatchingRequests,
  getDriverMapData,
  bootstrapDriverAccess,
  getDriverSession,
  issueDriverQrSale,
  loginDriverByKey,
  logoutDriverSession,
  notifyPickupChange,
  redeemPassengerQrSale,
  resetDriverRidePickup,
  sendDriverLocation,
  setDriverOnlineStatus,
  setDriverRideStatus,
  updateDriverRidePickup,
  updateDriverRideRoute,
} from '../infrastructure/api/driverApi'

export {
  confirmPickup,
  rateRideAsPassenger,
  completeOnboarding,
  createRequest,
  deleteRequest,
  getCurrentUser,
  getPricing,
  getRideQuote,
  getRequestById,
  getUserCabinet,
  listPublicMapMarks,
  listGroupSuggestions,
  listRideOffers,
  getRideOffer,
  bookRideOffer,
  listMatchingRideOffers,
  listMyRequests,
  listServiceZones,
  purchasePointsByCard,
  transferPoints,
  issuePassengerQrSale,
  updateCurrentUserLanguage,
  updateRequest,
} from '../infrastructure/api/passengerApi'

export {
  createAdminInfoBlock,
  deleteAdminInfoBlock,
  getAdminUnreadCount,
  getDriverUnreadCount,
  getPassengerUnreadCount,
  listAdminInfoBlocks,
  listAdminNotifications,
  listDriverNotifications,
  listPassengerNotifications,
  markAdminNotificationRead,
  markAllAdminNotificationsRead,
  markAllDriverNotificationsRead,
  markAllPassengerNotificationsRead,
  markDriverNotificationRead,
  markPassengerNotificationRead,
} from '../infrastructure/api/notificationsApi'

export type { CreateInfoBlockPayload } from '../infrastructure/api/notificationsApi'

export {
  approveDriverApplication,
  getDriverApplication,
  getDriverCabinetEnterUrl,
  getDriverRegistrationForm,
  getDriverRegistrationSettings,
  getMyDriverApplication,
  listDriverApplications,
  rejectDriverApplication,
  submitDriverApplication,
  updateDriverRegistrationSettings,
  uploadDriverApplicationFile,
} from '../infrastructure/api/driverRegistrationApi'

export {
  blockUser,
  unblockUser,
  listBlockedUsers,
  blockUserAsDriver,
  unblockUserAsDriver,
  listBlockedUsersAsDriver,
} from '../infrastructure/api/blockApi'
